version: "3.2"
services:
  proxy:
    image: nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - "web"
    volumes:
      - ${PWD}/files/proxy_nginx.conf:/etc/nginx/nginx.conf:ro
      - proxy_confd:/etc/nginx/conf.d:ro
      - proxy_certs:/etc/ssl/private
    restart: always

  web:
    image: nginx:latest
    ports:
        - "10080:80"
    depends_on:
      - "php"
    volumes:
        - html:/var/www/html
        - web_confd:/etc/nginx/conf.d:ro
    links:
        - php
    restart: always

  php:
    image: sputnikdan/php-rpi:7.2-fpm
    volumes:
      - html:/var/www/html
    #environment:
    #  PHP_EXTENSION_XDEBUG: 1
    #  PHP_INI_XDEBUG__REMOTE_PORT: 10000
    #  PHP_IDE_CONFIG: "servername=localhost"
    #  XDEBUG_CONFIG: "remote_host=<debugger ip> remote_port=10000 remote_autostart=1"
    ports:
        - "9000:9000"
    restart: always

volumes:
  web_confd:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/files/web_conf.d"
  html:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/data/volumes/html"
  proxy_confd:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/files/proxy_conf.d"
  proxy_certs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/files/proxy_certs"

