web:
  image: nginx:latest
  ports:
      - "80:80"
  volumes:
      - /data/volumes/html:/var/www/html
      - ./files/web_conf.d:/etc/nginx/conf.d:ro
  links:
      - php
  restart: always

php:
  image: sputnikdan/php-rpi:7.2-fpm
  volumes:
    - /data/volumes/html:/var/www/html
  ports:
      - "9000:9000"
  restart: always
