version: "2"
services:
  web:
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - html:/var/www/html
        - nginx_confd:/etc/nginx/conf.d:ro
    links:
        - php
    restart: always

  php:
    image: sputnikdan/php-rpi:7.2-fpm
    volumes:
      - html:/var/www/html
    ports:
        - "9000:9000"
    restart: always

volumes:
  nginx_confd:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/files/web_conf.d"
  html:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/volumes/html
