web:
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - ../../volumes/html:/code
        - ../../volumes/web/default.conf:/etc/nginx/conf.d/default.conf
    links:
        - php

php:
    image: sputnikdan/php-rpi:7.2-fpm
    volumes: 
        - ../../volumes/html:/code
