web:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - ../../volumes/html:/code
        - ../../volumes/web/default.conf:/etc/nginx/conf.d/default.conf
    links:
        - php

php:
    image: asaa/php-rpi
    volumes: 
        - ../../volumes/html:/code
